#! /bin/bash
log_folder="build_logs_$(date +%Y-%m-%d_%H-%M-%S)"
mkdir -p logs
mkdir -p logs/$log_folder
sudo docker build . -t "ingsw" --network=host --build-arg CACHE_DATE=$(date +%Y-%m-%d_%H-%M-%S) --build-arg GROUP_ID="group-01" --build-arg GROUP_REPO="https://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@github.com/AndreaRZH/ing-sw-2021-zhabjaku-santillan-tabacchi" --build-arg GROUP_DIR="ing-sw-2021-zhabjaku-santillan-tabacchi"  | tee logs/$log_folder/group-01_RAW.txt
sudo docker build . -t "ingsw" --network=host --build-arg CACHE_DATE=$(date +%Y-%m-%d_%H-%M-%S) --build-arg GROUP_ID="group-04" --build-arg GROUP_REPO="https://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@github.com/leonardo-panseri/ing-sw-2021-panseri-spada-mornatta" --build-arg GROUP_DIR="ing-sw-2021-panseri-spada-mornatta"  | tee logs/$log_folder/group-04_RAW.txt
sudo docker build . -t "ingsw" --network=host --build-arg CACHE_DATE=$(date +%Y-%m-%d_%H-%M-%S) --build-arg GROUP_ID="group-09" --build-arg GROUP_REPO="https://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@github.com/AlessandroPozzoni/ing-sw-2021-saglimbeni-ramos-pozzoni.git" --build-arg GROUP_DIR="ing-sw-2021-saglimbeni-ramos-pozzoni.git"  | tee logs/$log_folder/group-09_RAW.txt
sudo docker build . -t "ingsw" --network=host --build-arg CACHE_DATE=$(date +%Y-%m-%d_%H-%M-%S) --build-arg GROUP_ID="group-22" --build-arg GROUP_REPO="https://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@github.com/ravifrancesco/ing-sw-2021-srinivasan-tiu-urso" --build-arg GROUP_DIR="ing-sw-2021-srinivasan-tiu-urso"  | tee logs/$log_folder/group-22_RAW.txt
sudo docker build . -t "ingsw" --network=host --build-arg CACHE_DATE=$(date +%Y-%m-%d_%H-%M-%S) --build-arg GROUP_ID="group-25" --build-arg GROUP_REPO="https://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@github.com/AntonioScapellato/ing-sw-2021-Scapellato-Circo-Secci" --build-arg GROUP_DIR="ing-sw-2021-Scapellato-Circo-Secci"  | tee logs/$log_folder/group-25_RAW.txt
sudo docker build . -t "ingsw" --network=host --build-arg CACHE_DATE=$(date +%Y-%m-%d_%H-%M-%S) --build-arg GROUP_ID="group-40" --build-arg GROUP_REPO="https://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@github.com/ScaccabarozziMatteo/ing-sw-2021-Scaccabarozzi-Tenemaya-Usai" --build-arg GROUP_DIR="ing-sw-2021-Scaccabarozzi-Tenemaya-Usai"  | tee logs/$log_folder/group-40_RAW.txt
sudo docker build . -t "ingsw" --network=host --build-arg CACHE_DATE=$(date +%Y-%m-%d_%H-%M-%S) --build-arg GROUP_ID="group-54" --build-arg GROUP_REPO="https://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@github.com/piergiorgioprosperi/ing-sw-2021-piovesan-prosperi-salamone" --build-arg GROUP_DIR="ing-sw-2021-piovesan-prosperi-salamone"  | tee logs/$log_folder/group-54_RAW.txt
